service: blindtable

plugins:
  - serverless-webpack

custom:
  - webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs4.3
  stage: prod
  region: us-west-2

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-west-2:*:*"


functions:
  create:
    handler: create.main
    events:
      - http:
          path: reservations
          method: post
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-west-2:672685466128:userpool/us-west-2_HCBMXRMZx
  get:
    handler: get.main
    events:
      - http:
          path: reservations/{id}
          method: get
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-west-2:672685466128:userpool/us-west-2_HCBMXRMZx
  list:
    handler: list.main
    events:
      - http:
          path: reservations
          method: get
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-west-2:672685466128:userpool/us-west-2_HCBMXRMZx
  update:
    handler: update.main
    events:
      - http:
          path: reservations/{id}
          method: put
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-west-2:672685466128:userpool/us-west-2_HCBMXRMZx
  delete:
    handler: delete.main
    events:
      - http:
          path: reservations/{id}
          method: delete
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-west-2:672685466128:userpool/us-west-2_HCBMXRMZx

#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
#    events:
#      - http:
#          path: users/create
#          method: get
#      - s3: ${env:BUCKET}
#      - schedule: rate(10 minutes)
#      - sns: greeter-topic
#      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
#      - alexaSkill
#      - iot:
#          sql: "SELECT * FROM 'some_topic'"
#      - cloudwatchEvent:
#          event:
#            source:
#              - "aws.ec2"
#            detail-type:
#              - "EC2 Instance State-change Notification"
#            detail:
#              state:
#                - pending

#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
